---
title: "Autosomal Slope Analysis"
output:
  pdf_document: 
      latex_engine: xelatex
  html_document: default
date: "2025-11-20"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(readxl)
library(dplyr)
library(ggplot2)
library(tibble)
library(tidyr)


data <- read_excel("PLCO_longitudinal_mCAs_0s.xlsx") 

df1 <- data[data$type_FINAL %in% c("Gain", "Loss", "CN-LOH"), ]

auto <- df1[!(df1$chrom == "chrX"),]

```

# Models 

### Becky's Model 

```{r}

auto <- auto %>%
  mutate(
    age_65 = age_at_collection - 65,
    smoking_status = factor(smoking_status, levels = c("Never", "Former", "Current"))
  )

auto_pos <- auto  %>%
  filter(cf_FINAL > 0)

orig <- lmer(cf_FINAL ~ age_65 + 
                  smoking_status + 
                  smoking_status*age_65 +
                  (age_65|plco_id / mca_num), 
                 data=auto_pos)

summary(orig)

```

### LME 

```{r}
library(dplyr)
library(lme4)

auto_lme <- lmer(
  cf_FINAL ~ age_65 * smoking_status + 
    (1 + age_65 | plco_id / mca_num),
  data = auto_pos,
  REML = FALSE
)

summary(auto_lme)
```

### GLMMIX

```{r}

auto <- auto %>%
  mutate(
    cf_binary = ifelse(cf_FINAL > 0, 1, 0),
    age_65 = age_at_collection - 65,
    smoking_status = factor(smoking_status, levels = c("Never", "Former", "Current"))
  )

auto_glmmix <- glmer(
  cf_binary ~ age_65 * smoking_status + 
    (1 + age_65 | plco_id / mca_num),
  family = binomial(link = "probit"),
  data = auto
)

summary(auto_glmmix)
```

### Hurdle Model 

```{r}

library(dplyr)
library(brms)

auto <- auto %>%
  mutate(
    Ipos = as.integer(cf_FINAL > 0),
    cf_pos = if_else(cf_FINAL > 0, cf_FINAL, NA_real_),
    age_65 = age_at_collection - 65,
    smoking_status = factor(smoking_status, levels = c("Never", "Former", "Current")),
    plco_id = factor(plco_id),
    mca_num = factor(mca_num)
  )

auto_hurdle <- brm(
  bf(
    Ipos ~ age_65 * smoking_status +
      (1 + age_65 | p | plco_id) +
      (1 | q | plco_id:mca_num),
    family = bernoulli(link = "probit")
  ) +
  bf(
    cf_pos | subset(Ipos == 1) ~ age_65 * smoking_status +
      (1 + age_65 | p | plco_id) +
      (1 | q | plco_id:mca_num),
    family = gaussian()
  ),
  data = auto,
  backend = "cmdstanr",
  chains = 4,
  cores = 4,
  iter = 1500,
  warmup = 750,
  control = list(adapt_delta = 0.99, max_treedepth = 15),
  init = 0
)

print(summary(auto_hurdle), digits = 3)

```

### Hurdle Table 

```{r}
results <- data.frame(
  Term = c(
    "B0", "B1", "B2_Former", "B2_Current", "B3_Former", "B3_Current",
    "alpha0", "alpha1", "alpha2_Former", "alpha2_Current", "alpha3_Former", "alpha3_Current",
    "sigma(b0_i)", "sigma(b1_i)", "sigma(c0_i)", "sigma(c1_i)",
    "cor(b0_i,b1_i)", "cor(b0_i,c0_i)", "cor(b1_i,c0_i)", "cor(b0_i,c1_i)",
    "cor(b1_i,c1_i)", "cor(c0_i,c1_i)",
    "sigma(b0_ij)", "sigma(b1_ij)", "sigma(c0_ij)", "sigma(c1_ij)",
    "cor(b0_ij,b1_ij)", "cor(b0_ij,c0_ij)", "cor(b1_ij,c0_ij)",
    "cor(b0_ij,c1_ij)", "cor(b1_ij,c1_ij)", "cor(c0_ij,c1_ij)",
    "sigma(e)"
  ),
  
  Combined_Estimate = c(
    0.115, 0.006, -0.010, 0.004, 0.001, -0.001,
    0.344, 0.012, -0.033, 0.074, -0.001, -0.017,
    0.433, 0.044, 0.088, 0.014,
    -0.295, 0.560, -0.159, -0.032, 0.870, 0.108,
    0.334, NA, 0.088, NA,
    NA, 0.345, NA, NA, NA, NA,
    0.036
  ),
  
  Combined_SE = c(
    0.008, 0.001, 0.011, 0.017, 0.001, 0.002,
    0.049, 0.008, 0.066, 0.110, 0.010, 0.018,
    0.055, 0.008, 0.005, 0.001,
    0.184, 0.103, 0.157, 0.107, 0.075, 0.072,
    0.066, NA, 0.003, NA,
    NA, 0.121, NA, NA, NA, NA,
    0.002
  ),
  
  Separate_Estimate = c(
    0.115, 0.006, -0.010, 0.003, 0.001, -0.001,
    0.347, 0.006, -0.016, 0.069, -0.008, -0.015,
    0.093, 0.013, 0.393, 0.011,
    0.000, NA, NA, NA, NA, NA,
    0.074, 0.005, 0.257, 0.003,
    0.540, NA, NA, NA, NA, 1.000,
    0.031
  ),
  
  Separate_SE = c(
    0.008, 0.001, 0.011, 0.017, 0.001, 0.002,
    0.046, 0.007, 0.062, 0.101, 0.009, 0.017,
    NA, NA, NA, NA,
    NA, NA, NA, NA, NA, NA,
    NA, NA, NA, NA,
    NA, NA, NA, NA, NA, NA,
    NA
  )
)

print(results)
```


### Tobit Model 

```{r}
library(brms)

censor_point <- min(auto$cf_FINAL[is.finite(auto$cf_FINAL)])

auto$cf_FINAL[!is.finite(auto$cf_FINAL)] <- censor_point
auto$cens_type <- ifelse(auto$cf_FINAL == censor_point, -1, 0)

auto_tobit <- brm(
  bf(
    cf_FINAL | cens(cens_type) ~ age_65 * smoking_status +
      (1 + age_65 | ID1 | plco_id) +
      (1 + age_65 | ID2 | plco_id:mca_num)
  ),
  family = gaussian(),
  data = auto,
  chains = 4,
  cores = 4
)

print(summary(auto_tobit), digits = 3)

```
### Tobit Table 

```{r}
results <- data.frame(
  Term = c(
    "Intercept", 
    "age_65",
    "smoking_Former",
    "smoking_Current",
    "age_65:smoking_Former",
    "age_65:smoking_Current",

    "sigma(b0_i)", 
    "sigma(b1_i)", 
    "cor(b0_i,b1_i)",

    "sigma(b0_ij)", 
    "sigma(b1_ij)", 
    "cor(b0_ij,b1_ij)",

    "sigma(e)"
  ),
  
  Estimate = c(
    0.047,
    0.004,
   -0.005,
    0.001,
   -0.001,
   -0.001,
    0.086,
    0.003,
   -0.097,
    0.070,
    0.007,
    0.816,
    0.115
  ),
  
  SE = c(
    0.007,
    0.001,
    0.010,
    0.017,
    0.002,
    0.003,
    0.006,
    0.002,
    0.345,
    0.005,
    0.001,
    0.116,
    0.002
  )
)

print(results)
```


## Figure

### LME Plot 

```{r}

library(lme4)
library(ggplot2)
library(dplyr)
library(tidyr)
library(ggeffects)

age_fix <- function(x) {
  x + 65
}

# Create plot
plot_curve <- function(lmer_model, predict_term, graph_name) {
  
  Profile <- predict_response(lmer_model, terms = predict_term)
  
  plot(Profile) +
    labs(x = "Age (Years)", y = "Clonal Fraction") +
    scale_color_manual(
      values = c(
        "Never" = "#D55E00",
        "Current" = "#0072B2",
        "Former" = "#009E73"
      )
    ) +
    scale_fill_manual(
      values = c(
        "Never" = "#D55E00",
        "Current" = "#0072B2",
        "Former" = "#009E73"
      )
    ) +
    scale_x_continuous(label = age_fix, limits = c(-11, 14),
                       breaks = c(-10, -5, 0, 5, 10, 14)) +
    ggtitle(graph_name) +
    theme_minimal() +
    theme(legend.position = "none")
}


auto_fit <- lmer(cf_FINAL ~ age_65 + 
                  smoking_status + 
                  smoking_status*age_65 +
                  (age_65|plco_id / mca_num), 
                 data=auto)

summary(auto_fit)


#Create Graph for results
p_lme <- plot_curve(auto_fit, 
                      predict_term = c("age_65","smoking_status"),
                      "Autosomal") +
  labs(title = NULL,x = NULL, y = NULL, smoking_status = "Smoking Status") +
  scale_x_continuous(label = age_fix, limits = c(-11,14), breaks = c(-10,-5,0,5,10,14)) +
  scale_y_continuous(limits = c(-0.10, 0.60), breaks = c(0.00,0.10,0.20,0.30,0.40,0.50,0.60)) +
  theme_minimal() + 
  theme(
  legend.position = "none",
  axis.title.x = element_text(size = 18),
  axis.title.y = element_text(size = 18),
  axis.text.x = element_text(size = 14),
  axis.text.y = element_text(size = 14),
  plot.title = element_text(size = 20, face = "bold"),
  legend.title = element_text(size = 16),
  legend.text = element_text(size = 14)
)

#Inspect Graph
p_lme

ggsave("Auto_LMM.pdf", p_lme, width = 6, height = 5)

```


## Hurdle Plot 

```{r}

library(dplyr)
library(tidyr)
library(ggplot2)

age_fix <- function(x) {
  x + 65
}

# Prediction grid
pred_grid <- expand_grid(
  age_65 = seq(min(auto$age_65, na.rm = TRUE),
               max(auto$age_65, na.rm = TRUE),
               length.out = 100),
  smoking_status = levels(auto$smoking_status),
  Ipos = 1L
)

# Get predictions for positive part
p_cf_df <- fitted(
  auto_hurdle,
  newdata = pred_grid,
  resp = "cfpos",
  re_formula = NA,
  summary = TRUE
) %>%
  as.data.frame() %>%
  bind_cols(pred_grid)

p_cf_df$smoking_status <- factor(
  p_cf_df$smoking_status,
  levels = c("Never", "Former", "Current")
)

p_hurdle <- ggplot(p_cf_df, aes(x = age_65, y = Estimate, color = smoking_status, fill = smoking_status)) +
  geom_ribbon(aes(ymin = Q2.5, ymax = Q97.5), alpha = 0.10, color = NA) +
  geom_line(linewidth = 1) +
  labs(title = NULL, x = NULL, y = NULL) +
  scale_color_manual(
    values = c(
      "Never" = "#D55E00",
      "Current" = "#0072B2",
      "Former" = "#009E73"
    )
  ) +
  scale_fill_manual(
    values = c(
      "Never" = "#D55E00",
      "Current" = "#0072B2",
      "Former" = "#009E73"
    )
  ) +
  scale_x_continuous(
    labels = age_fix,
    limits = c(-11, 14),
    breaks = c(-10, -5, 0, 5, 10, 14)
  ) +
  scale_y_continuous(
    limits = c(-0.10, 0.60),
    breaks = c(0.00, 0.10, 0.20, 0.30, 0.40, 0.50, 0.60)
  ) +
  theme_minimal() +
  theme(
  legend.position = "none",
  axis.title.x = element_text(size = 18),
  axis.title.y = element_text(size = 18),
  axis.text.x = element_text(size = 14),
  axis.text.y = element_text(size = 14),
  plot.title = element_text(size = 20, face = "bold"),
  legend.title = element_text(size = 16),
  legend.text = element_text(size = 14)
)

# Show plot
p_hurdle

ggsave("Auto_hurdle.pdf", p_hurdle, width = 6, height = 5)

```


## Tobit Plot 

```{r}
library(brms)
library(ggplot2)
library(dplyr)
library(tidyr)
library(ggeffects)
library(specr)

p_tobit <- plot_curve(
  auto_tobit,
  predict_term = c("age_65", "smoking_status"),
  "Autosomal"
) +
  labs(
    title = NULL,
    x = NULL, y = NULL,
    smoking_status = "Smoking Status"
  ) +
  scale_x_continuous(
    labels = age_fix,
    limits = c(-11, 14),
    breaks = c(-10, -5, 0, 5, 10, 14)
  ) +
  scale_y_continuous(
    limits = c(-0.10, 0.60),
    breaks = c(0.00, 0.10, 0.20, 0.30, 0.40, 0.50, 0.60)
  ) +
  theme_minimal() +
  theme(
  legend.position = "none",
  axis.title.x = element_text(size = 18),
  axis.title.y = element_text(size = 18),
  axis.text.x = element_text(size = 14),
  axis.text.y = element_text(size = 14),
  plot.title = element_text(size = 20, face = "bold"),
  legend.title = element_text(size = 16),
  legend.text = element_text(size = 14)
)

p_tobit

ggsave("Auto_tobit.pdf", p_tobit, width = 6, height = 5)

```

```{r}
library(cowplot)

legend <- get_legend(
  p_tobit +
    theme(legend.position = "bottom")
)

plot_grid(legend)

ggsave(
  "legend.pdf",
  legend,
  width = 6,
  height = 1
)
```

