---
title: "mLOY Slope Models"
output: html_document
date: "2025-12-16"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(readxl)
library(dplyr)
library(ggplot2)
library(tibble)
library(tidyr)


data <- read_excel("PLCO_longitudinal_mCAs_0s.xlsx") 

mloy <- data  %>%
  filter(type_FINAL == "mLOY")

```


# Models 

### Becky's Model 

```{r}

mloy <- mloy %>%
  mutate(
    age_65 = age_at_collection - 65,
    smoking_status = factor(smoking_status, levels = c("Never", "Former", "Current"))
  )

mloy_pos <- mloy  %>%
  filter(cf_FINAL > 0)

mloy_orig <- lmer(cf_FINAL ~ age_65 + 
                  smoking_status + 
                  smoking_status*age_65 +
                  (age_65|plco_id), 
                 data=mloy_pos)

summary(mloy_orig)

```

### LME 

```{r}
library(dplyr)
library(lme4)

mloy_lme <- lmer(
  cf_FINAL ~ age_65 * smoking_status + 
    (1 + age_65 | plco_id),
  data = mloy_pos,
  REML = FALSE
)

summary(mloy_lme)
```



### GLMMIX

```{r}

mloy <- mloy %>%
  mutate(
    cf_binary = ifelse(cf_FINAL > 0, 1, 0),
    age_65 = age_at_collection - 65,
    smoking_status = factor(smoking_status, levels = c("Never", "Former", "Current"))
  )

mloy_glmmix <- glmer(
  cf_binary ~ age_65 * smoking_status + 
    (1 + age_65 | plco_id),
  family = binomial(link = "probit"),
  data = mloy
)

summary(mloy_glmmix)
```


### Hurdle model 

```{r}

library(dplyr)
library(brms)

mloy <- mloy %>%
  mutate(
    Ipos = as.integer(cf_FINAL > 0),
    cf_pos = ifelse(cf_FINAL > 0, cf_FINAL, NA_real_),
    age_65 = age_at_collection - 65,
    smoking_status = factor(smoking_status, levels = c("Never", "Former", "Current"))
  )

mloy_hurdle <- brm(
  bf(
    Ipos ~ age_65 * smoking_status + (1 + age_65 | p | plco_id),
    family = bernoulli(link = "probit")
  ) +
  bf(
    cf_pos | subset(Ipos == 1) ~ age_65 * smoking_status + (1 + age_65 | p | plco_id),
    family = gaussian()
  ),
  data = mloy,
  backend = "cmdstanr",
  threads = threading(4),
  chains = 4,
  cores = 4,
  iter = 1500,
  warmup = 750,
  sample_prior = "no",
  control = list(
    adapt_delta = 0.99,
    max_treedepth = 12
  )
)

print(summary(mloy_hurdle), digits = 3)
```



### Hurdle Table 

```{r}
results <- data.frame(
  Term = c(
    "B0", "B1", 
    "B2_Former", "B2_Current",
    "B3_Former", "B3_Current",
    "alpha0", "alpha1",
    "alpha2_Former", "alpha2_Current",
    "alpha3_Former", "alpha3_Current",
    
    "sigma(b0)", "sigma(b1)",
    "sigma(c0)", "sigma(c1)",
    "cor(b0,b1)", "cor(b0,c0)", "cor(b1,c0)",
    "cor(b0,c1)", "cor(b1,c1)", "cor(c0,c1)", "sigma(e)"
  ),
  
  Combined_Estimate = c(
    0.197, 0.021,
  0.047, 0.070,
 -0.003, -0.005,
  2.683, 0.263,
  0.554, 1.059,
 -0.055, -0.080,
  0.154, 0.010,
  2.199, 0.159,
  0.248, 0.934, -0.046,
  0.878, 0.348, 0.019, 0.034
  ),
  
  Combined_SE = c(
    0.009, 0.001,
    0.012, 0.018,
    0.001, 0.002,
    0.270, 0.039,
    0.256, 0.374,
    0.037, 0.055,
    0.004, 0.001,
    0.222, 0.028,
    0.051, 0.023, 0.154,
    0.081, 0.070, 0.185, 0.001
  ),
  
  Separate_Estimate = c(
    0.198, 0.021,
    0.045, 0.071,
   -0.003, -0.005,
    4.045, 0.023,
    0.176, 0.305,
   -0.001, 0.016,
    0.153, 0.009,
    4.155, 0.112,
    0.240, NA, NA,
    NA, NA, NA, 0.040
  ),
  
  Separate_SE = c(
    0.010, 0.001,
    0.012, 0.018,
    0.001, 0.002,
    0.204, 0.034,
    0.244, 0.430,
    0.041, 0.073,
    NA, NA,
    NA, NA,
    NA, NA, NA,
    NA, NA, NA, NA
  )
)

print(results)

```


### Tobit Model 

```{r}
library(brms)

censor_point <- min(mloy$cf_FINAL[is.finite(mloy$cf_FINAL)])

mloy$cf_FINAL[!is.finite(mloy$cf_FINAL)] <- censor_point

mloy$cens_type <- ifelse(mloy$cf_FINAL == censor_point, -1, 0)

mloy_tobit <- brm(
  bf(
    cf_FINAL | cens(cens_type) ~ age_65 * smoking_status + (1 + age_65 | p | plco_id)
  ),
  family = gaussian(),
  data = mloy,
  chains = 4,
  cores = 4
)

print(summary(mloy_tobit), digits = 3)
```
### Tobit Table 

```{r}
results <- data.frame(
  Term = c(
    "Intercept", 
    "age_65",
    "smoking_Former",
    "smoking_Current",
    "age_65:smoking_Former",
    "age_65:smoking_Current",
    "sigma(b0)", 
    "sigma(b1)", 
    "p(rho)", 
    "sigma(e)"
  ),
  
  Estimate = c(
    0.192,
    0.021,
    0.047,
    0.071,
   -0.003,
   -0.005,
    0.158,
    0.010,
    0.259,
    0.040
  ),
  
  SE = c(
    0.010,
    0.001,
    0.012,
    0.018,
    0.001,
    0.002,
    0.004,
    0.001,
    0.058,
    0.001
  )
)

print(results)

```



## Figure 

### LME Plot 

```{r}

library(lme4)
library(ggplot2)
library(dplyr)
library(tidyr)
library(ggeffects)

age_fix <- function(x) {
  x + 65
}

# Create plot

plot_curve <- function(lmer_model, predict_term, graph_name) {
  
  Profile <- predict_response(lmer_model, terms = predict_term)
  
  plot(Profile) +
    labs(x = "Age (Years)", y = "Clonal Fraction") +
    scale_color_manual(
      values = c(
        "Never" = "#D55E00",
        "Current" = "#0072B2",
        "Former" = "#009E73"
      )
    ) +
    scale_fill_manual(
      values = c(
        "Never" = "#D55E00",
        "Current" = "#0072B2",
        "Former" = "#009E73"
      )
    ) +
    scale_x_continuous(label = age_fix, limits = c(-11, 14),
                       breaks = c(-10, -5, 0, 5, 10, 14)) +
    ggtitle(graph_name) +
    theme_minimal() +
    theme(legend.position = "none")
}

mLOY_fit <- lmer(cf_FINAL ~ age_65 + 
                  smoking_status + 
                  smoking_status*age_65 +
                  (age_65|plco_id), 
                 data=mloy)

summary(mLOY_fit)


#Create Graph for results

p_lme <- plot_curve(mloy_lme, 
                      predict_term = c("age_65","smoking_status"),
                      "mLOY") +
  labs(title = NULL, x = NULL, y = NULL, smoking_status = "Smoking Status") +
  scale_x_continuous(label = age_fix, limits = c(-11,14), breaks = c(-10,-5,0,5,10,14)) +
  scale_y_continuous(limits = c(-0.10, 0.60), breaks = c(0.00,0.10,0.20,0.30,0.40,0.50,0.60)) +
  theme_minimal() +
   theme(
  legend.position = "none",
  axis.title.x = element_text(size = 18),
  axis.title.y = element_text(size = 18),
  axis.text.x = element_text(size = 14),
  axis.text.y = element_text(size = 14),
  plot.title = element_text(size = 20, face = "bold"),
  legend.title = element_text(size = 16),
  legend.text = element_text(size = 14)
)

#Inspect Graph
p_lme

ggsave("mLOY_LMM.pdf", p_lme, width = 6, height = 5)

```

## Hurdle Plot 

```{r}

library(dplyr)
library(tidyr)
library(ggplot2)

age_fix <- function(x) {
  x + 65
}

# Prediction grid
pred_grid <- expand_grid(
  age_65 = seq(min(mloy$age_65, na.rm = TRUE),
               max(mloy$age_65, na.rm = TRUE),
               length.out = 100),
  smoking_status = levels(mloy$smoking_status),
  Ipos = 1L
)

# Get predictions for positive part
p_cf_df <- fitted(
  mloy_hurdle,
  newdata = pred_grid,
  resp = "cfpos",
  re_formula = NA,
  summary = TRUE
) %>%
  as.data.frame() %>%
  bind_cols(pred_grid)

p_cf_df$smoking_status <- factor(
  p_cf_df$smoking_status,
  levels = c("Never", "Former", "Current")
)

p_hurdle <- ggplot(p_cf_df, aes(x = age_65, y = Estimate, color = smoking_status, fill = smoking_status)) +
  geom_ribbon(aes(ymin = Q2.5, ymax = Q97.5), alpha = 0.10, color = NA) +
  geom_line(linewidth = 1) +
  labs(title = NULL, x = NULL, y = NULL) +
  scale_color_manual(
    values = c(
      "Never" = "#D55E00",
      "Current" = "#0072B2",
      "Former" = "#009E73"
    )
  ) +
  scale_fill_manual(
    values = c(
      "Never" = "#D55E00",
      "Current" = "#0072B2",
      "Former" = "#009E73"
    )
  ) +
  scale_x_continuous(
    labels = age_fix,
    limits = c(-11, 14),
    breaks = c(-10, -5, 0, 5, 10, 14)
  ) +
  scale_y_continuous(
    limits = c(-0.10, 0.60),
    breaks = c(0.00, 0.10, 0.20, 0.30, 0.40, 0.50, 0.60)
  ) +
  theme_minimal() +
  theme(
  legend.position = "none",
  axis.title.x = element_text(size = 18),
  axis.title.y = element_text(size = 18),
  axis.text.x = element_text(size = 14),
  axis.text.y = element_text(size = 14),
  plot.title = element_text(size = 20, face = "bold"),
  legend.title = element_text(size = 16),
  legend.text = element_text(size = 14)
)

# Show plot
p_hurdle

ggsave("mLOY_hurdle.pdf", p_hurdle, width = 6, height = 5)


```

## Tobit Plot 

```{r}
library(brms)
library(ggplot2)
library(dplyr)
library(tidyr)
library(ggeffects)

p_tobit <- plot_curve(
  mloy_tobit,
  predict_term = c("age_65", "smoking_status"),
  "mLOY"
) +
  labs(
    title = NULL,
    x = NULL, y = NULL,
    smoking_status = "Smoking Status"
  ) +
  scale_x_continuous(
    labels = age_fix,
    limits = c(-11, 14),
    breaks = c(-10, -5, 0, 5, 10, 14)
  ) +
  scale_y_continuous(
    limits = c(-0.10, 0.60),
    breaks = c(0.00, 0.10, 0.20, 0.30, 0.40, 0.50, 0.60)
  ) +
  theme_minimal() +
  theme(
  legend.position = "none",
  axis.title.x = element_text(size = 18),
  axis.title.y = element_text(size = 18),
  axis.text.x = element_text(size = 14),
  axis.text.y = element_text(size = 14),
  plot.title = element_text(size = 20, face = "bold"),
  legend.title = element_text(size = 16),
  legend.text = element_text(size = 14)
)

p_tobit

ggsave("mLOY_tobit.pdf", p_tobit, width = 6, height = 5)

```



```{r}

mLOY_plot <- p_lme + p_hurdle + p_tobit +
  plot_layout(ncol = 3)

mLOY_plot

ggsave("mLOY_plots.png", mLOY_plot, width = 14, height = 4)

```

